// import '../app/main_dependencies.dart';

// List<Doctor> doctors = [
//   Doctor(
//     "Dr. Ahmad",
//     'Ahmed Mohamed',
//     'Ali',
//     'Male',
//     'ahmed@gmail.com',
//     'specialty',
//     "https://images.theconversation.com/files/304957/original/file-20191203-66986-im7o5.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop",
//     'assets/profile.jpg',
//     'prefix',
//     0,
//     'medicalEducation',
//     'residency',
//     'internship',
//     'fellowship',
//     'biography',
//   ),
//   Doctor(
//     "Dr. Mahmod",
//     'Mahmod',
//     'Abdalla',
//     'Male',
//     'mahmod@gmail.com',
//     'specialty',
//     "https://images.theconversation.com/files/304957/original/file-20191203-66986-im7o5.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop",
//     'assets/profile.jpg',
//     'prefix',
//     1,
//     'medicalEducation',
//     'residency',
//     'internship',
//     'fellowship',
//     'biography',
//   ),
//   Doctor(
//     "Dr. Qasim",
//     'Qasim',
//     'Mahmod',
//     'Male',
//     'oasim@gmail.com',
//     'specialty',
//     "https://jac.ae/wp-content/uploads/2019/10/slide-doctors-2.jpg",
//     'assets/profile.jpg',
//     'prefix',
//     2,
//     'medicalEducation',
//     'residency',
//     'internship',
//     'fellowship',
//     'biography',
//   ),
//   Doctor(
//     "Dr. Omar",
//     'Omar Mohamed',
//     'Eltablawy',
//     'Male',
//     'Eltablawy@gmail.com',
//     'Dermatologists',
//     "https://www.independent.ie/irish-news/education/671f1/40328133.ece/AUTOCROP/w620/A%20young%20caring%20doctor",
//     'assets/profile.jpg',
//     'prefix',
//     3,
//     'medicalEducation',
//     'residency',
//     'internship',
//     'fellowship',
//     'Eugene Sobngwi is Professor of Endocrinology and Metabolism at the University of Yaoundé s1 and Consultant Endocrinologist at Yaoundé Central Hospital. He is head of the Laboratory of Molecular Medicine and Metabolism at the Biotechnology Centre of the University of Yaoundé 1.',
//   ),
//   Doctor(
//     "Dr. Ali",
//     'Ali',
//     'Hamed',
//     'Male',
//     'hamed@gmail.com',
//     'specialty',
//     "https://www.woninstitute.edu/wp-content/uploads/2021/01/360_F_317854905_2idSdvi2ds3yejmk8mhvxYr1OpdVTrSM.jpg",
//     'assets/profile.jpg',
//     'prefix',
//     4,
//     'medicalEducation',
//     'residency',
//     'internship',
//     'fellowship',
//     'biography',
//   ),
//   Doctor(
//     "Dr. Abdullah",
//     'Abdullah',
//     'Mahmoud',
//     'Male',
//     'abdullah Mahmoud',
//     'specialty',
//     "https://i.guim.co.uk/img/media/ce9c149506881191caa4b1f838575d0dbb07e520/734_381_6827_4098/master/6827.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=c38e5e77b9f3882e14b633932e18cea5",
//     'assets/profile.jpg',
//     'prefix',
//     5,
//     'medicalEducation',
//     'residency',
//     'internship',
//     'fellowship',
//     'biography',
//   ),
// ];
