### Use this file to test out your REST call before implementing them in the code

# Local JSON-Server
### Change the IP address below to your PC's IP address. Remain the port number 3000 unchanged
# @baseUrl = http://192.168.0.5:3000

# Local Firebase Emulator 
#@baseUrl = http://192.168.100.40:5001/patientaid-206bb/us-central1/api
# @baseUrl = https://us-central1-patientaid-206bb.cloudfunctions.net/api
@baseUrl = https://us-central1-final-year-project---final.cloudfunctions.net/api

# Live Firebase
# @baseUrl = https://us-central1-mvvm-frontend-and-mvc-backend.cloudfunctions.net/api

### Request 1 : Get a user whose correct 'login' and 'password'
### Purpose   : To simulate the authentication process. 
GET {{baseUrl}}/users?login=omar@gmail.com&password=123456789

### Request 2 : Get the counter data  for a given user
GET {{baseUrl}}/doctors

### Request 3 : Update the information of a given counter
PUT {{baseUrl}}/users/ewons54sm68mr31byaNd
Content-Type: application/json

{
    "name": "omar Eltablawy",
    "id": "user4"
}

### Request: Get all users
GET {{baseUrl}}/hospitals

### Request: Add a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
    
    "name": "omar",
    "login": "",
    "email": "omar@gmail.com",
    "password": "123456",
    "phoneNumber": "0156456",
    "photoUrl": "assets/mathew.png",
    "appointment": null,
    "hasAppointment": false
}


### Request: Delete a user
POST {{baseUrl}}/Appointments
Content-Type: application/json

{
    "name": "omar",
    "approve": true,
    "disapprove": true,
    "hospitalName": "KPJ",
    "docotorId": 2,
    "userId": 26,
    "day": "2021-07-05 13:30:00.000Z",
    "isSelected": true
}

### Request: Delete a user
POST {{baseUrl}}/hospitals
Content-Type: application/json

{
    "name": "Mohmand Hospital",
    "description": "Kandahar Hospital",
}

### Request: Delete a user
PATCH {{baseUrl}}/doctors/12
Content-Type: application/json

{
    "gender": "Female"
}

### Request: Delete a user
GET {{baseUrl}}/users/zFCdaJwClvsEOANAisOy


### Request: Delete a user
GET {{baseUrl}}/users?id=81C3QFA7wIYFjFrufQUuMHR7fus1

### Request: Delete a user
GET {{baseUrl}}/doctors/

### Request: Delete a user
DELETE {{baseUrl}}/users/ewons54sm68mr31byaNd

###

POST {{baseUrl}}/doctors
Content-Type: application/json

{
     
            "hospitalId": "cDC6hwkUkM6aWlb14Mjf",
            "name": "Sha Wali",
            "firstName": "Shah",
            "lastName": "Wali",
            "gender": "Male",
            "email": "shah@gmail.com",
            "password": "1234567",
            "specialty": "Surgeon",
            "imageURL": "assets/albert.png",
            "imagePath": "assets/albert.png",
            "prefix": "prefix",
            "rank": 3.25,
            "medicalEducation": "MBA",
            "residency": "Kandahar",
            "internship": "Already done",
            "fellowship": "fellowship",
            "biography": "Not ready yet"
}


###

POST {{baseUrl}}/hospitals
Content-Type: application/json

{   
            "latitude": "",
            "hospitalName": "Mujaddadi Hospital 2",
            "description": "Good Hospital 1",
            "hospitalId": 3,
            "location": "Kandahar",
            "longitude": "",
            "imageURL": ""
}

